---
- hosts: pg_master
  roles:
    - name: postgres
      become: yes
    - name: master
      become: yes

- hosts: pg_slave
  roles:
    - name: postgres
      become: yes
    - name: slave
      become: yes
