---
- hosts: pg_master
  tasks:
    - name: Create a database
      postgresql_db:
        name: replication_test_database
      become: yes
      become_user: postgres

- hosts: pg_slave
  tasks:
    - name: Verify db exists
      shell: "psql -d replication_test_database"
      become: yes
      become_user: postgres

- hosts: pg_master
  tasks:
    - name: Remove the test database
      postgresql_db:
        name: replication_test_database
        state: absent
      become: yes
      become_user: postgres